// example/nestjs-react-ssr/web/components/search/index.tsx
import { useStore } from 'ssr-common-utils'
import { useSnapshot } from 'valtio'
import styles from './index.module.less'

function Search() {
	const { searchState } = useStore<{ searchState: { searchText: string } }>()
	const snap = useSnapshot(searchState)
	const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		searchState.searchText = e.target.value
	}
	const toSearch = () => {
		const searchVal = searchState.searchText
		location.href = `https://search.youku.com/search_video?keyword=${searchVal}`
	}
	return (
		<div className={styles.searchContainer}>
			<input type="text" className={styles.input} value={snap.searchText ?? ''} onChange={handleChange} placeholder="该搜索框内容会在所有页面共享" />
			<img src="https://img.alicdn.com/tfs/TB15zSoX21TBuNjy0FjXXajyXXa-48-48.png" alt="" className={styles.searchImg} onClick={toSearch} />
		</div>
	)
}

export default Search

// example/nestjs-vue3-ssr-pinia/web/components/search/index.vue
<template>
  <div class="searchContainer">
    <input :value="searchText" type="text" class="input" placeholder="该搜索框内容会在所有页面共享" @input="setText">
    <img src="https://img.alicdn.com/tfs/TB15zSoX21TBuNjy0FjXXajyXXa-48-48.png" alt="" class="searchImg" @click="toSearch">
  </div>
</template>

<script lang="ts" setup>
import { useSearchStore } from '@/pinia-store'
const store = useSearchStore()
const searchText = store.searchText

const setText = (e: any) => {
  store.setData({
    text: e.target.value
  })
}
const toSearch = () => {
  location.href = `https://search.youku.com/search_video?keyword=${searchText}`
}
</script>

<style lang="less" scoped>
@import "./index.less";
</style>
