// example/spa/web/components/slider/index.tsx
import React from 'react'
import Swiper from 'react-id-swiper'
import 'swiper/css/swiper.css'
import styles from './index.less'

function Slider (props) {
  const data = props.data[0]
  const params = {
    pagination: {
      el: '.swiper-pagination',
      clickable: true,
      loop: true
    }
  }
  return (
    <div className={styles.carouselContainer}>
      <Swiper {...params}>
        {
          data.itemMap.map(val => (
            <div className={styles.sliderContainer} key={val.img} onClick={() => props.history.push('/detail/cbba934b14f747049187')}>
              <img src={val.img} className={styles.carouselImg} />
              <div className={styles.sliderDescContainer}>
                <span className={styles.sliderTitle}>
                  { val.title }
                </span>
              </div>
            </div>
          )
          )
        }
      </Swiper>
    </div>
  )
}

export default Slider

// example/nestjs-vue-ssr/web/components/slider/index.vue
<template>
  <div class="swiperContainer">
    <Swiper ref="mySwiper" :options="swiperOptions">
      <swiper-slide v-for="val in data[0].itemMap" :key="val.img" class="sliderContainer">
        <img :src="val.img" class="carouselImg" @click="toDetail" />
        <div class="sliderDescContainer">
          <span class="sliderTitle">
            {{ val.title }}
          </span>
        </div>
      </swiper-slide>
      <template #pagination class="swiper-pagination" />
    </Swiper>
  </div>
</template>

<script lang="ts">
import { Swiper, SwiperSlide, directive } from "vue-awesome-swiper";
import "swiper/css/swiper.min.css";

export default {
  components: {
    Swiper,
    SwiperSlide,
  },
  directives: {
    swiper: directive,
  },
  props: ["data"],
  data() {
    return {
      swiperOptions: {
        pagination: {
          el: ".swiper-pagination",
          clickable: true,
          loop: true,
        },
      },
    };
  },
  computed: {
    swiper() {
      return this.$refs.mySwiper.$swiper;
    },
  },
  mounted() {
    this.swiper.slideTo(2, 1000, false);
  },
  methods: {
    toDetail() {
      this.$router.push("/detail/cbba934b14f747049187");
    },
  },
};
</script>

<style lang="less" scoped>
@import "./index.less";
</style>
