// example/nestjs-react-ssr/web/components/brief/index.tsx
import React from 'react'
import { BriefDataNode } from '@/interface'
import styles from './index.less'

interface Props {
  data: BriefDataNode[]
}
function Brief (props: Props) {
  const data = props.data[0].data
  return (
    <div className={styles['brief-info']}>
      <div className={styles['brief-title']}>
        <span className={styles['icon-GOLDEN']}>{data.mark.data.text}</span>
        <h1>{data.showName}</h1>
      </div>
      <div className={styles['brief-score']}>
        {
          data.subTitleList.map((item, index) => {
            return (
              item.subtitle && (
                <span className={`${(item.subtitleType === 'PLAY_VV' && styles.hotVv) || ''}`} key={`subtile${index}`}>
                  {
                    item.subtitleType === 'PLAY_VV'
                      ? <img src={data.heatIcon} />
                      : (index > 0) ? (<span className={styles.divide}>/</span>) : ''
                  }
                  <span>{item.subtitle}</span>
                </span>
              )
            )
          })
        }
      </div>
    </div>
  )
}

export default Brief

// example/midway-vue3-ssr/web/components/brief/index.vue

<template>
  <div class="brief-info">
    <div class="brief-title">
      <span class="['icon-GOLDEN']">{{ briefData.mark.data.text }}</span>
      <h1>{{ briefData.showName }}</h1>
    </div>
    <div class="brief-score">
      <span v-for="(item, index) in briefData.subTitleList" :key="item.subtitle" :class="item.subtitleType === 'PLAY_VV' ? 'hotVv' : ''">
        <img v-if=" item.subtitleType === 'PLAY_VV'" :src="briefData.heatIcon" alt="">
        <span v-if="index > 0" class="divide">/</span>
        <span>{{ item.subtitle }}</span>
      </span>
    </div>
  </div>
</template>

<script>

export default {
  props: ['data'],
  data () {
    return {
      briefData: this.data[0].data
    }
  }
}
</script>

<style lang="less" scoped>
@import "./index.less";
</style>
