// example/nestjs-vue-ssr/web/components/search/index.vue

<template>
  <div class="searchContainer">
    <input :value="searchText" type="text" class="input" placeholder="该搜索框内容会在所有页面共享" @input="setText">
    <img src="https://img.alicdn.com/tfs/TB15zSoX21TBuNjy0FjXXajyXXa-48-48.png" alt="" class="searchImg" @click="toSearch">
  </div>
</template>

<script>
import { mapState } from 'vuex'

export default {
  computed: {
    ...mapState({
      searchText: state => state.searchStore.searchText
    })
  },

  methods: {
    setText (e) {
      this.$store.dispatch('searchStore/setText', {
        payload: {
          text: e.target.value
        }
      })
    },
    toSearch () {
      location.href = `https://search.youku.com/search_video?keyword=${this.searchText}`
    }
  }
}
</script>

<style lang="less" scoped>
@import "./index.less";
</style>

// example/spa/web/components/search/index.tsx
import React, { useContext } from 'react'
import styles from './index.less'

function Search (props) {
  const { state, dispatch } = useContext(window.STORE_CONTEXT)
  const handleChange = e => {
    dispatch({
      type: 'updateContext',
      payload: {
        search: {
          text: e.target.value
        }
      }
    })
  }
  return (
    <div className={styles.searchContainer}>
      <input type="text" className={styles.input} value={state.search?.text} onChange={handleChange} placeholder="该搜索框内容会在所有页面共享"/>
      <img src="https://img.alicdn.com/tfs/TB15zSoX21TBuNjy0FjXXajyXXa-48-48.png" alt="" className={styles.searchImg} />
    </div >
  )
}

export default Search
