// example/nestjs-react-ssr/web/pages/index/render.tsx
import { SProps } from 'ssr-types'
import Slider from '@/components/slider'
import Rectangle from '@/components/rectangle'
import Search from '@/components/search'
import { IData } from '~/typings/data'
import { useStore } from 'ssr-common-utils'

export default function Index(props: SProps) {
	const { indexState: state } = useStore<{ indexState: IData }>()
	return (
		<div>
			<Search></Search>
			{state?.indexData?.data?.[0]?.components ? (
				<div>
					<Slider {...props} data={state.indexData.data[0].components} />
					<Rectangle {...props} data={state.indexData.data[1].components} />
				</div>
			) : (
				<img src="https://gw.alicdn.com/tfs/TB1v.zIE7T2gK0jSZPcXXcKkpXa-128-128.gif" className="loading" />
			)}
		</div>
	)
}

// example/midway-vue-ssr/web/pages/index/render.vue

<template>
  <div>
    <!-- <Search></Search>
      {
        state?.indexData?.data?.[0]?.components ? <div>
          <Slider {...props} data={state.indexData.data[0].components} />
          <Rectangle {...props} data={state.indexData.data[1].components} />
        </div> : <img src='https://gw.alicdn.com/tfs/TB1v.zIE7T2gK0jSZPcXXcKkpXa-128-128.gif' className='loading' />
      } -->
    indexPage
  </div>
</template>

<script>
// import Slider from '@/components/slider'
// import Rectangle from '@/components/rectangle'
// import Search from '@/components/search'
// export default {
//   name: 'Index',
//   components: {
//     Slider,
//     Rectangle,
//     Search
//   }
// }
</script>

<style>

</style>
