// example/midway-vue3-ssr/web/components/recommend/index.vue
<template>
  <div>
    <div class="title">为你推荐</div>
    <div class="reContainer">
      <div v-for="item in data" :key="item.data.heat" class="reContent">
        <img :src="item.data.img" />
        <div class="vTitle">
          {{ item.data.title }}
        </div>
        <div class="subTitle">
          {{ item.data.subtitle }}
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { RecommendDataNode } from "~/typings/data";

defineProps<{
  data: RecommendDataNode[];
}>();
</script>

<style lang="less" scoped>
@import "./index.less";
</style>

// example/midway-react-ssr/web/components/recommend/index.tsx
import { RecommendDataNode } from '~/typings/data'
import styles from './index.module.less'

interface Props {
  data: RecommendDataNode[]
}

function Recommend (props: Props) {
  const data = props.data
  return (
    <div>
      <div className={styles.title}>
        为你推荐
      </div>
      <div className={styles.reContainer}>
        {
          data.map(item => (
            <div key={item.data.heat} className={styles.reContent}>
              <img src={item.data.img} />
              <div className={styles.vTitle}>
                {item.data.title}
              </div>
              <div className={styles.subTitle}>
                {item.data.subtitle}
              </div>
            </div>
          ))
        }
      </div>
    </div>
  )
}

export default Recommend
