// example/nestjs-vue-ssr/web/components/slider/index.vue
<template>
  <div class="swiperContainer">
    <Swiper ref="mySwiper" :options="swiperOptions">
      <swiper-slide v-for="val in data[0].itemMap" :key="val.img" class="sliderContainer">
        <img :src="val.img" class="carouselImg" @click="toDetail" />
        <div class="sliderDescContainer">
          <span class="sliderTitle">
            {{ val.title }}
          </span>
        </div>
      </swiper-slide>
      <template #pagination class="swiper-pagination" />
    </Swiper>
  </div>
</template>

<script lang="ts">
import { Swiper, SwiperSlide, directive } from "vue-awesome-swiper";
import "swiper/css/swiper.min.css";

export default {
  components: {
    Swiper,
    SwiperSlide,
  },
  directives: {
    swiper: directive,
  },
  props: ["data"],
  data() {
    return {
      swiperOptions: {
        pagination: {
          el: ".swiper-pagination",
          clickable: true,
          loop: true,
        },
      },
    };
  },
  computed: {
    swiper() {
      return this.$refs.mySwiper.$swiper;
    },
  },
  mounted() {
    this.swiper.slideTo(2, 1000, false);
  },
  methods: {
    toDetail() {
      this.$router.push("/detail/cbba934b14f747049187");
    },
  },
};
</script>

<style lang="less" scoped>
@import "./index.less";
</style>

// example/nestjs-react-ssr/web/components/slider/index.tsx
import React from 'react'
import { SProps } from 'ssr-types-react'
import { ItemMapArr } from '@/interface'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/swiper.min.css'
import styles from './index.module.less'

// 示例代码特殊处理 swiper 的 useLayoutEffect 在服务端渲染报错，实际应用可自行删除
React.useLayoutEffect = React.useEffect

interface Props extends SProps {
  data: ItemMapArr[]
}

const params = {
  pagination: {
    el: '.swiper-pagination',
    clickable: true,
    loop: true
  }
}

function Slider (props: Props) {
  const data = props.data[0]
  return (
    <div className={styles.swiperContainer}>
      <Swiper {...params}>
        {
          data.itemMap.map(val => (
            <SwiperSlide key={val.img} >
              <div className={styles.sliderContainer} onClick={() => props.history.push('/detail/cbba934b14f747049187')}>
                <img src={val.img} className={styles.carouselImg} />
                <div className={styles.sliderDescContainer}>
                  <span className={styles.sliderTitle}>
                    {val.title}
                  </span>
                </div>
              </div>
            </SwiperSlide>
          )
          )
        }
      </Swiper>
    </div>
  )
}

export default Slider
