// example/nestjs-vue3-ssr-pinia/web/pages/detail/render$id.vue
<template>
  <div>
    <Search />
    <template v-if="detailData">
      <Player :data="detailData[0].dataNode" />
      <Brief :data="detailData[1].dataNode" />
      <Recommend :data="detailData[2].dataNode" />
    </template>
    <template v-else>
      <img
        src="https://gw.alicdn.com/tfs/TB1v.zIE7T2gK0jSZPcXXcKkpXa-128-128.gif"
        class="loading"
      />
    </template>
  </div>
</template>

<script lang="ts" setup>
import Player from "@/components/player/index.vue";
import Brief from "@/components/brief/index.vue";
import Recommend from "@/components/recommend/index.vue";
import Search from "@/components/search/index.vue";
import { useDetailStore } from "@/pinia-store";

const detailStore = useDetailStore();
const detailData = detailStore.data;
</script>

<style></style>

// example/spa/web/pages/detail/render$id.tsx
import React from 'react'
import Player from '@/components/player'
import Brief from '@/components/brief'
import Recommend from '@/components/recommend'

export default (props) => {
  return (
    <div>
      {
        props.data ? <div>
          <Player data={props.data[0].dataNode} />
          <Brief data={props.data[1].dataNode} />
          <Recommend data={props.data[2].dataNode} />
        </div> : <img src='https://gw.alicdn.com/tfs/TB1v.zIE7T2gK0jSZPcXXcKkpXa-128-128.gif' className='loading' />
      }
    </div>
  )
}
