// example/midway-vue-ssr/web/components/recommend/index.vue
<template>
  <div>
    <div class="title">为你推荐</div>
    <div class="reContainer">
      <div v-for="item in data" :key="item.data.heat" class="reContent">
        <img :src="item.data.img" />
        <div class="vTitle">
          {{ item.data.title }}
        </div>
        <div class="subTitle">
          {{ item.data.subtitle }}
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
export default {
  props: ["data"],
};
</script>

<style lang="less" scoped>
@import "./index.less";
</style>

// example/spa/web/components/recommend/index.tsx
import React from 'react'
import styles from './index.less'

function Recommend (props) {
  const data = props.data
  return (
    <div>
      <div className={styles.title}>
        为你推荐
      </div>
      <div className={styles.reContainer}>

        {
          data.map(item => (
            <div key={item.data.heat} className={styles.reContent}>
              <img src={item.data.img} />
              <div className={styles.vTitle}>
                {item.data.title}
              </div>
              <div className={styles.subTitle}>
                {item.data.subtitle}
              </div>
            </div>
          ))
        }
      </div>
    </div>
  )
}

export default Recommend
