// example/midway-vue-ssr/web/components/rectangle/index.vue
<template>
  <div class="pbbContainer">
    <div v-for="val in data[0].itemMap" :key="val.img" class="pbbItemContainer">
      <div class="pbbDescContainer">
        <div
          class="defaultItemBg"
          :style="{ background: `url(${val.img}) 0 0 /cover` }"
          @click="toDetail"
        />
        <div class="pName pbbName">
          {{ val.title }}
        </div>
        <div class="pDesc pbbName">
          {{ val.subtitle }}
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
export default {
  props: ["data"],
  methods: {
    toDetail() {
      this.$router.push("/detail/cbba934b14f747049187");
    },
  },
};
</script>

<style lang="less" scoped>
@import "./index.less";
</style>

// example/midway-react-ssr/web/components/rectangle/index.tsx
import styles from './index.module.less'

function Rectangle (props) {
  const data = props.data[0]
  return (
    <div className={styles.pbbContainer}>
      {
        data.itemMap.map(val => {
          const imgUrl = val.img
          return (
            <div className={styles.pbbItemContainer} key={val.img} onClick={() => props.history.push('/detail/cbba934b14f747049187')}>
              <div className={styles.pbbDescContainer}>
                <div className={styles.defaultItemBg} style={{
                  background: `url('${imgUrl}') 0  0 /cover`
                }} />
                <div className={`${styles.pName} ${styles.pbbName}`} >
                  { val.title }
                </div>
                <div className={`${styles.pDesc} ${styles.pbbName}`}>
                  {val.subtitle}
                </div>
              </div>
            </div>
          )
        })
      }
    </div >
  )
}

export default Rectangle
