// example/serverless-ssr-app/web/components/slider/index.tsx
import React from 'react'
import Swiper from 'react-id-swiper'
import { SProps } from 'ssr-types'
import { ItemMapArr } from '@/interface'
import 'swiper/css/swiper.css'
import styles from './index.less'

interface Props extends SProps {
  data: ItemMapArr[]
}

const params = {
  pagination: {
    el: '.swiper-pagination',
    clickable: true,
    loop: true
  }
}

function Slider (props: Props) {
  const data = props.data[0]
  return (
    <div className={styles.swiperContainer}>
      <Swiper {...params}>
        {
          data.itemMap.map(val => (
            <div className={styles.sliderContainer} key={val.img} onClick={() => props.history.push('/detail/cbba934b14f747049187')}>
              <img src={val.img} className={styles.carouselImg} />
              <div className={styles.sliderDescContainer}>
                <span className={styles.sliderTitle}>
                  {val.title}
                </span>
              </div>
            </div>
          )
          )
        }
      </Swiper>
    </div>
  )
}

export default Slider

// example/nestjs-vue3-ssr-pinia/web/components/slider/index.vue
<template>
  <div class="swiperContainer">
    <Swiper ref="mySwiper">
      <swiper-slide v-for="val in data[0].itemMap" :key="val.img" class="sliderContainer" @click="toDetail">
        <img :src="val.img" class="carouselImg">
        <div class="sliderDescContainer">
          <span class="sliderTitle">
            {{ val.title }}
          </span>
        </div>
      </swiper-slide>
      <template #pagination class="swiper-pagination" />
    </Swiper>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import { ItemMapArr } from '~/typings/data'
import 'swiper/swiper-bundle.css'
import { Swiper, SwiperSlide } from 'swiper/vue'
import { Swiper as SwiperCore, Autoplay, Pagination } from 'swiper'
import 'swiper/components/pagination/pagination.less'
const Router = useRouter()
SwiperCore.use([Autoplay, Pagination])
defineProps<{
	data: ItemMapArr[]
}>()
const toDetail = () => {
	Router.push('/detail/cbba934b14f747049187')
}
</script>

<style lang="less" scoped>
@import "./index.less";
</style>
