// example/midway-vue3-ssr/web/components/slider/index.vue
<template>
  <div class="swiperContainer">
    <Swiper ref="mySwiper">
      <swiper-slide v-for="val in data[0].itemMap" :key="val.img" class="sliderContainer" @click="toDetail">
        <img :src="val.img" class="carouselImg">
        <div class="sliderDescContainer">
          <span class="sliderTitle">
            {{ val.title }}
          </span>
        </div>
      </swiper-slide>
      <template #pagination class="swiper-pagination" />
    </Swiper>
  </div>
</template>

<script>
import 'swiper/swiper-bundle.css'
import { Swiper, SwiperSlide } from 'swiper/vue'
import SwiperCore, { Autoplay, Pagination } from 'swiper'
import 'swiper/components/pagination/pagination.less'

SwiperCore.use([Autoplay, Pagination])

export default {
  components: {
    Swiper,
    SwiperSlide
  },
  props: ['data'],

  mounted () {

  },
  methods: {
    toDetail () {
      this.$router.push('/detail/cbba934b14f747049187')
    }
  }
}
</script>

<style lang="less" scoped>
@import "./index.less";
</style>

// example/spa/web/components/slider/index.tsx
import React from 'react'
import Swiper from 'react-id-swiper'
import 'swiper/css/swiper.css'
import styles from './index.less'

function Slider (props) {
  const data = props.data[0]
  const params = {
    pagination: {
      el: '.swiper-pagination',
      clickable: true,
      loop: true
    }
  }
  return (
    <div className={styles.carouselContainer}>
      <Swiper {...params}>
        {
          data.itemMap.map(val => (
            <div className={styles.sliderContainer} key={val.img} onClick={() => props.history.push('/detail/cbba934b14f747049187')}>
              <img src={val.img} className={styles.carouselImg} />
              <div className={styles.sliderDescContainer}>
                <span className={styles.sliderTitle}>
                  { val.title }
                </span>
              </div>
            </div>
          )
          )
        }
      </Swiper>
    </div>
  )
}

export default Slider
